### ISSUE TITLE
Bioconductor version?

### ISSUE THREAD

**Issue by robertfisher002** [shdam/pairedGSEA#1]
I am using R 4.2.2 and Bioconductor 3.16 as suggested by the user guide but the package is not available: 

"Bioconductor version 3.16 (BiocManager 1.30.19), R 4.2.2 (2022-10-31)
Installing package(s) 'pairedGSEA'
Warning: package ‘pairedGSEA’ is not available for Bioconductor version '3.16'"

**Comment by shdam** [comment]
Hi Robert,

Thank you for pointing this out. I must have missed it when revising the guides.
While we hope to get the package on Bioconductor one day, it isn't currently.
For now, it's only available on Github with `devtools::install_github("shdam/pairedGSEA")`

Please let me know if you find the package useful, if you run into any issues, or if you have any comments or recommendations. 

Best regards, 
Søren
