### ISSUE TITLE
Paired_diff function returning only 1 significant surrogate variable

### ISSUE THREAD

**Issue by robertfisher002** [shdam/pairedGSEA#2]
HI Søren, 

I organized my data in a SummarizedExperiment like the example dataset, but when I run my data I am getting the following error message: "Error in group_feat[, 2] : subscript out of bounds" which is, I believe, due to the fact that my data returns only 1 significant surrogate variable compared to the example data which returns 2. I have looked through my SummarizedExperiment but I am not sure how to get 2 variables since I am just supplying that I want a comparison between two treatment groups (supplied as "1" or "2"). I also tried just running normal DESeq2 with my SummarizedExperiment and it worked fine. Here is the code I am running: 

```
set.seed(500) # For reproducible results

diff_results_1205 <- paired_diff(
  object = se,
  group_col = "Treatment",
  sample_col = "Sample",
  baseline = 1,
  case = 2,
  store_results = FALSE,
  quiet = TRUE
  )
```

and here is the summary of my SummarizedExperiment:
```

                   Sample   Cell_line Treatment Description
              <character> <character>  <factor> <character>
Corin_1205_1 Corin_1205_1      1205Lu         2   Corin_24h
Corin_1205_2 Corin_1205_2      1205Lu         2   Corin_24h
DMSO_1205_1   DMSO_1205_1      1205Lu         1    DMSO_24h
DMSO_1205_2   DMSO_1205_2      1205Lu         1    DMSO_24h

```
Here is the summary of the example data just for easy reference:
```
DataFrame with 6 rows and 5 columns
                 study          id                 source final_description group_nr
           <character> <character>            <character>       <character> <factor>
GSM1499784    GSE61220  GSM1499784 small airway epithel..       Epi,Control        1
GSM1499785    GSE61220  GSM1499785 small airway epithel..       Epi,Control        1
GSM1499786    GSE61220  GSM1499786 small airway epithel..       Epi,Control        1
GSM1499790    GSE61220  GSM1499790 small airway epithel..      Epi,TNF,12hr        2
GSM1499791    GSE61220  GSM1499791 small airway epithel..      Epi,TNF,12hr        2
GSM1499792    GSE61220  GSM1499792 small airway epithel..      Epi,TNF,12hr        2
```

Thanks for the help,
Robert

**Comment by shdam** [comment]
Hi Robert,

Thank you for raising the issue!

It seems to be because DEXSeq expects the row names of the SummarizedExperiment to be on the format of "gene:transcript" (e.g., "ENSG00000282880:ENST00000635453"). If you run with `deseq_only = TRUE`, it should run. Of course, you would not run a differential splicing analysis then.

I will look into a way of handling this error better and making it easier to add transcript information, where you won't have to manually format the row names.

I hope this answer is helpful to you. In short, the solution is to format the row names the way DEXSeq expects.

Let me know if you have any follow-up questions or run into any other peculiarities.

Best regards,
Søren

**Comment by robertfisher002** [comment]
Hi again,

I added in the transcript ID's and formatted the SummarizedExperiment identical to the example SE and I am still getting only 1 surrogate variable and the following error: 

Error in density.default(x, adjust = adj) : 'x' contains missing values

My SE:
`class: SummarizedExperiment 
dim: 27653 4 
metadata(0):
assays(1): counts
rownames(27653): ENSG00000211643:ENST00000390289 ENSG00000198888:ENST00000361390
  ... ENSG00000225630:ENST00000457540 ENSG00000248527:ENST00000514057
rowData names(0):
colnames(4): Corin_1205_1 Corin_1205_2 DMSO_1205_1 DMSO_1205_2
colData names(4): Sample Cell_line Treatment Description`

Example SE:
`class: SummarizedExperiment 
dim: 5611 6 
metadata(0):
assays(1): counts
rownames(5611): ENSG00000282880:ENST00000635453 ENSG00000282880:ENST00000635195
  ... ENSG00000249230:ENST00000504393 ENSG00000249244:ENST00000505994
rowData names(0):
colnames(6): GSM1499784 GSM1499785 ... GSM1499791 GSM1499792
colData names(5): study id source final_description group_nr`

I checked for the error online and it seems some people received this error if a row contains all 0 counts, but I have filtered those out and I still receive the error. 

Thanks,
Robert

**Comment by shdam** [comment]
Hi Robert, 

I am sorry to hear you are still having issues.

Would you mind sharing your data and function call settings, so I can look into the issue in more detail? - perhaps a downsampled version that still produces the error, if possible.

If you prefer to share it privately, my email is sohdam @ dtu.dk

Best regards,
Søren
